### PR TITLE
Adding three qubit custom controlled gate

### PR DESCRIPTION
**Pull request by stephendiadamo**
- Adds some tests
- Fixes some typos
- Renames shadowed variables in some parts of the code
- Adds some doc strings

### CODE REVIEW

**Review by benjione — APPROVED** [review]
Nice changes :+1:

**Comment by stephendiadamo** [comment]
@benjione One sec, for some reason the tests pass on my computer but not on Github... I'll clean up these commits and then we can merge

**Comment by stephendiadamo** [comment]
Alright, I gave up lol... The tests passes on my computer but hangs on Github... I don't want to exceed the run time on Github so I'll just skip the test that causes it to hang for now.

The main changes are in the files that aren't test files... mainly in the first commit

**Comment by benjione** [comment]
I tested it locally, the one test works for me as well. So does not seem to be a Linux issue.

I will just merge it anyway then :)

**Pull request merged**
